### ISSUE TITLE
Velocity无法加载

### ISSUE THREAD

**Issue by Xiaohuang257** [MossFrp/MossFrpClient-Java#5]
Velocity版本：3.1.2-SNAPSHOT-161
MossFrpJava版本：1.5.1.1.1213-Beta
[latest.log](https://github.com/MossFrp/MossFrpClient-Java/files/9071439/latest.log)

**Comment by MossCG** [comment]
this will be fixed in the next re-build version

**Comment by xiaozhu2007** [comment]
+1
```
[13:39:21 ERROR]: Unable to load plugin plugins/MossFrpJava.jar
com.velocitypowered.api.plugin.InvalidPluginException: Plugin ID 'MossFrp' is invalid.
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:72) ~[server.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:96) ~[server.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:345) ~[server.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:227) ~[server.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:69) ~[server.jar:3.2.0-SNAPSHOT (git-8a048f05-b220)]
```
